mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('paris/', include('paris.urls')),
    path('admin/', admin.site.urls),
]

paris/urls.py
from django.urls import path

from . import views


app_name = 'paris'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('history', views.HistoryView.as_view(), name='history'),
    path('bet',views.BetView.as_view(),name='bet'),
    path('bet_history2/<str:ev>/<str:strat>',
         views.BetHistory2.as_view(),
         name='bet_history2'),
    path('pred', views.PredictionView.as_view(), name='pred'),
    path('day/<str:date>/<str:strat>', views.DayView.as_view(), name='day')
    
]

paris/models.py
from django.db import models


MATCH_STATUS = [('Scheduled', 'Scheduled'),
                ('Live', 'Live'),
                ('Results', 'Results'),
                ('Rescheduled', 'Rescheduled'),
                ('Canceled', 'Canceled'),
                ('Expired', 'Expired'),
                ('Empty', 'Empty')]

BET_STATUS = [('Pending', 'Pending'),
              ('Finished', 'Finished'),
              ('Canceled', 'Canceled')]

WINNER = [('Team 1', 'Team 1'),
          ('Team 2', 'Team 2'),
          ('None', 'None')]

BET_STRATEGY = [('Naive', 'Naive'),
                ('EV', 'EV'),
                ('HLTV', 'HLTV')]

MODELS = [('LOGREG', 'LOGREG')]


class Match(models.Model):
    team1 = models.CharField(max_length=200)
    team2 = models.CharField(max_length=200)
    odd1 = models.DecimalField(max_digits=10, decimal_places=2)
    odd2 = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateTimeField('date scheduled')
    logo1 = models.CharField(max_length=200)
    logo2 = models.CharField(max_length=200)
    status = models.CharField(max_length=200, choices=MATCH_STATUS)
    bo = models.CharField(max_length=200)
    match_id = models.IntegerField(primary_key=True)
    winner = models.CharField(max_length=200, choices=WINNER)
    time_to_go = models.CharField(max_length=200)

    def __str__(self):
        return "%s vs %s" % (self.team1, self.team2)


class Prediction(models.Model):
    match = models.OneToOneField(Match,
                                 on_delete=models.CASCADE,
                                 primary_key=True)
    odd1 = models.DecimalField(max_digits=100, decimal_places=2)
    odd2 = models.DecimalField(max_digits=100, decimal_places=2)
    delta_ev_1 = models.DecimalField(max_digits=100,
                                     decimal_places=2,
                                     default=0)
    delta_ev_2 = models.DecimalField(max_digits=100,
                                     decimal_places=2,
                                     default=0)
    model = models.CharField(max_length=200, choices=MODELS)

    def __str__(self):
        return "Prediction of %s" % (self.match)


class Bet(models.Model):
    class Meta:
        constraints = [models.UniqueConstraint(fields=['match', 'strategy'],
                                               name='unique strat')]
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    winner = models.CharField(max_length=200, choices=WINNER, default='None')
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    status = models.CharField(max_length=200,
                              choices=BET_STATUS,
                              default='Pending')
    gain = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    real = models.BooleanField(default=False)
    strategy = models.CharField(max_length=200,
                                choices=BET_STRATEGY,
                                default='EV')
    bet_id = models.AutoField(primary_key=True)

    def __str__(self):
        return f"{self.amount:.2f}€  on {self.winner} ({self.match.team1} vs {self.match.team2}), strat : {self.strategy}" 

paris/forms.py
from django import forms
from .models import Bet,Match

from django.db.models import Q

class BetForm(forms.ModelForm):


	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['match'].queryset = Match.objects.filter(Q(status='Scheduled')|Q(status='Live')).order_by('date')

		'''if 'match' in self.data:
			try:

				match_id = int(self.data.get('match'))
				team1 = Match.objects.filter(match_id=match_id)[0].team1.strip()
				team2 = Match.objects.filter(match_id=match_id)[0].team2.strip()
				self.fields['winner'].choices = [(team1,team1),(team2,team2)]
				print([(team1,team1),(team2,team2)])
				

			except (ValueError, TypeError):
				pass  # invalid input from the client; ignore and fallback to empty City queryset
				'''


	class Meta:
		model = Bet
		fields = ['amount','match','winner']
		

paris/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.db.models import Q
from django.utils import timezone
from datetime import datetime, timedelta
import pytz
from .utils import compute_time_to_go
from .forms import BetForm
from .models import Match, Bet, Prediction
import numpy as np


MATCH_NOT_FINISHED = Q(status='Scheduled') | Q(status='Live')
DATA_DIR = 'var/'


class IndexView(generic.TemplateView):
    template_name = 'paris/index.html'
    context_object_name = ''

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        matches = Match.objects.filter(MATCH_NOT_FINISHED).order_by('date')
        compute_time_to_go(matches)
        context['matches'] = matches
        context['bets'] = Bet.objects.order_by('-match__date')
        context['total'] = np.array(list(map(lambda x: x.gain,Bet.objects.filter(status='Finished')))).sum()
        return context


def get_bets_list_by_ev(request):
    ev_trsh = request.GET.get('ev')
    data = {'bets': Bet.objects.filter(ev__gte=ev_trsh)}
    return render(request, '/bet_history', data)


class DayView(generic.ListView):
    template_name = 'paris/day.html'
    context_object_name = 'matches'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        strategy = self.kwargs['strat']
        date_ = self.kwargs['date']
        date_ = datetime.strptime(date_, "%d.%m.%Y")
        tz = timezone.get_current_timezone()
        date_ = tz.localize(date_, is_dst=None)
        print(date_)
        date_next_day = date_ + timedelta(days=1)
        IN_DAY = Q(date__gte=date_, date__lt=date_next_day)
        NOT_BET = Q(status='Rescheduled')|Q(status='Canceled')|Q(status='Expired')
        matches = Match.objects.filter(IN_DAY).exclude(NOT_BET).filter(prediction__pk__isnull=False).order_by('-date')
        compute_time_to_go(matches)
 
        if strategy == 'ev':
            bets = Bet.objects.filter(match__in=matches,
                                      strategy='EV').order_by('-match__date')
        elif strategy == 'kelly':
            bets = Bet.objects.filter(match__in=matches,
                                      strategy='Kelly').order_by('-match__date')
        elif strategy == 'naive':
            bets = Bet.objects.filter(match__in=matches,
                                      strategy='Naive').order_by('-match__date')
        print(len(bets),len(matches))
        context['mbs'] = zip(matches, bets)
        return context

    def get_queryset(self):
       
        return None


class BetView(generic.CreateView):
    template_name = 'paris/bet_form.html'
    model = Bet
    form_class = BetForm
    success_url = reverse_lazy('paris:index')


class BetHistory2(generic.ListView):
    template_name = 'paris/bet_history2.html'
    context_object_name = 'bets'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        strategy = self.kwargs['strat']
        context['strategy'] = strategy
        ev = self.kwargs['ev']
        if strategy == 'ev':
            bets = Bet.objects.filter(strategy='EV')

        elif strategy == 'naive':
            bets = Bet.objects.filter(strategy='Naive')

        elif strategy == 'kelly':
            bets = Bet.objects.filter(strategy='Kelly')

        n = 20
        date_0 = timezone.now().replace(second=0, minute=0,
                                        hour=0, microsecond=0)
        dates = [date_0-timezone.timedelta(days=i)
                 for i in range(-1, n)]
        totals = []
        for i in range(0, n+1):
            date_next_day = dates[i] + timedelta(days=1)
            bets_today = (bets.filter(match__date__lt=date_next_day,
                                      match__date__gte=dates[i])
                              .order_by('-match__date'))
            totals.append(np.array(list(map(lambda x: x.gain, bets_today))).sum())
        context['totals'] = dict(zip(dates, totals))
        context['total'] = np.array(totals, dtype=np.float).sum()
        return context

    def get_queryset(self):
        return None


class PredictionView(generic.ListView):
    template_name = 'paris/pred.html'
    context_object_name = 'pred_list'

    def get_queryset(self):
        return (Prediction.objects
                          .order_by('-match__date')
                          .filter(MATCH_NOT_FINISHED))


class HistoryView(generic.ListView):
    template_name = 'paris/history.html'
    context_object_name = 'matches_history'

    def get_queryset(self):
        return Match.objects.exclude(MATCH_NOT_FINISHED).order_by('-date')

paris/templates/paris/base.html
{% load static %}

<!DOCTYPE html>


<html>
  <head>
    <meta charset="utf-8">

    <title>     {% block title %}Base Page    {% endblock %} </title>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel='stylesheet' href='{% static "paris/style.css" %}'>

  </head>
  <body>





<div class = "d-flex flex-row justify-content-around " >
<div id='matchlist'>
  {% block matches %}{% endblock %}

</div>
<div id='predlist'>

{% block predictions %}{% endblock %}

  </div>

</div>



{% block script %}
<script >   

  $("#history").click(function (){
    
    $("#matchlist").load('{% url "paris:history" %}');
    $("#betform").load('{% url "paris:bet_history" %}');
    $("#predlist").html(' ')
    $('#upcoming').removeClass('active');
    $('#history').addClass('active');

    });

  $("#upcoming").click(function (){
    $("#matchlist").load('{% url "paris:upcoming" %}');
    $("#betform").load('{% url "paris:bet" %}');
    $("#predlist").load('{% url "paris:pred" %}');

    $('#upcoming').addClass('active');
    $('#history').removeClass('active');
    });

</script>

{% endblock script %}
  </body>
</html>

paris/templates/paris/bet_form.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<form method="post" action="{% url 'paris:bet' %}">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

<!--
<script>




$('#id_match').change(function() {

	var hello;
	var match_id = $(this).val();


	$.ajax({
		url: ' url "paris:ajax_team_match_list" ',

		data: {
			'match' : match_id 
		},

		success: function (data) {
			$('#id_winner').html(data);

		}
	});


})
	</script> -->

paris/templates/paris/bet_history.html
{% if bets %}

{% if total >= 0 %}
<h2 class = 'text-success'> 

{% else %}
<h2 class = 'text-danger'> 

{% endif %}

Gain = {{total}} </h2>

 
<table class="table table-striped">
  <thead>
    <tr>

      <th scope="col">Team 1</th>
      <th scope="col">Odd 1</th>
      <th scope="col">Team 2</th>
      <th scope="col">Odd 2</th>
      <th scope="col">Amount</th>
      <th score="col">EV</th> 
      <th scope="col">Bet</th>

      <th scope="col">Results</th>
      <th score="col">Status</th>
      <th score="col">Gain</th>

    </tr>
  </thead>
  <tbody>
    {% for bet in bets %}
    {% if bet.winner == bet.match.winner %}
    <tr class = 'bg-success'>
    {% elif bet.status == 'Pending' %}
        <tr class = 'bg-warning'>
    {% else %}
    <tr class = 'bg-danger'>
    {% endif %}

      <td>{{bet.match.team1}}</td>
      <td>{{bet.match.odd1}}</td>
      <td>{{bet.match.team2}}</td>
      <td>{{bet.match.odd2}}</td>
      <td>{{bet.amount}}€</td>
      <td>{% if bet.winner == 'Team 1' %}
       {{ bet.match.prediction.delta_ev_1}}
       {% else %}
       {{bet.match.prediction.delta_ev_2}}
       {% endif %}
      </td>
      {% if bet.winner == 'Team 1' %}
      <td>{{bet.match.team1}}</td>
      {% elif bet.winner == 'Team 2' %}
      <td>{{bet.match.team2}}</td>
      {% endif %}
      {% if bet.match.winner == 'Team 1' %}
      <td>{{bet.match.team1}}</td>
      {% elif bet.match.winner == 'Team 2' %}
      <td>{{bet.match.team2}}</td>
      {% else %}
      <td></td>
      {% endif %}
      <td>{{bet.status}}</td>
      <td>{{bet.gain}}</td>
    </tr>
{% endfor %}
  </tbody>
</table> 


{% else %}
    <p>No bet are available.</p>
{% endif %}

paris/templates/paris/bet_history2.html
{% if total >= 0 %}
<h2 class = 'text-success'> 

{% else %}
<h2 class = 'text-danger'> 

{% endif %}
Gain = {{total}} </h2>

<table class="table table-striped">
  <thead>
    <tr>

      <th scope="col">Date</th>
      <th scope="col">Gain</th>


    </tr>
  </thead>
  <tbody>
{% for date,total in totals.items%}
  <tr data-href='day/{{date|date:"d.m.Y"}}/{{strategy}}'> 
      <td>{{date|date:"d M"}}</td>
      {% if total >= 0 %}
      <td class='text-success'>
        {% else %}
              <td class='text-danger'>
            {% endif %}
      {{total}}</td>
    </tr>

{% endfor %}
  </tbody>
</table> 
<script>
  $('tr[data-href]').on("click", function() {
    document.location = $(this).data('href');
  });
</script>

paris/templates/paris/history.html
{% if matches_history %}
{% for match in matches_history %}

          {% if match.status == 'Canceled' %} 
          <div class="lounge-bets-items__item sys-betting bet-canceled" > <a href="/fr/match/211045/" class="lounge-match"> <div class="lounge-match__header"> <div class="lounge-match__date"> <div class="lounge-match-date  lounge-match-date_canceled  "> <div class="lounge-match-date__date sys-time-fixed"> {{match.date}} </div>   <div class="lounge-match-date__canceled">Match annulé</div>  </div> </div> <div class="lounge-match__tournament sys-tourney-name"> Tournoi </div> </div> <div class="lounge-match__body"> <div class="lounge-match__teams-bo"> <div class="lounge-match__team lounge-match__team_left"> <div class="lounge-team lounge-team_left sys-team-left   lounge-team_RUB "> <div class="lounge-team__info"> <div class="lounge-team__title sys-t1name"> {{match.team1}} </div> <div class="lounge-team__coeff-sum"> <div class="lounge-team__coeff sys-stat-koef-1">x{{match.odd1}}</div> </div> </div> <div class="lounge-team__logo"> <img src="{{match.logo1}}" alt="{{match.team1}}" class="sys-t1logo"> </div> </div> </div> <div class="lounge-match__bo sys-bo">  {{match.bo}}  </div> <div class="lounge-match__team lounge-match__team_right"> <div class="lounge-team lounge-team_right sys-team-right   lounge-team_RUB "> <div class="lounge-team__info"> <div class="lounge-team__title sys-t2name"> {{match.team2}} </div> <div class="lounge-team__coeff-sum"> <div class="lounge-team__coeff sys-stat-koef-2">x{{match.odd2}}</div> </div> </div> <div class="lounge-team__logo"><img src="{{match.logo2}}" alt="{{match.team2}}" class="sys-t2logo"> </div> </div> </div> </div> <div class="lounge-match__tournament-img sys-tourney-pic" style="background-image: url('https://csgolounge.com/images/leagues/go/2030_1586056352.png')"></div> </div> </a> </div>

          {% elif match.status == 'Rescheduled' %}

          <div class="lounge-bets-items__item sys-betting bet-rescheduled" > <a href="/fr/match/210799/" class="lounge-match"> <div class="lounge-match__header"> <div class="lounge-match__date"> <div class="lounge-match-date  lounge-match-date_rescheduled  "> <div class="lounge-match-date__date sys-time-fixed">  </div>  {{match.date}} <div class="lounge-match-date__rescheduled">Match repoussé</div>  </div> </div> <div class="lounge-match__tournament sys-tourney-name"> Tournoi </div> </div> <div class="lounge-match__body"> <div class="lounge-match__teams-bo"> <div class="lounge-match__team lounge-match__team_left"> <div class="lounge-team lounge-team_left sys-team-left   lounge-team_RUB "> <div class="lounge-team__info"> <div class="lounge-team__title sys-t1name"> {{match.team1}} </div> <div class="lounge-team__coeff-sum"> <div class="lounge-team__coeff sys-stat-koef-1">x{{match.odd1}}</div> </div> </div> <div class="lounge-team__logo"> <img src="{{match.logo1}}" alt="{{match.team1}}" class="sys-t1logo"> </div> </div> </div> <div class="lounge-match__bo sys-bo">  {{match.bo}}  </div> <div class="lounge-match__team lounge-match__team_right"> <div class="lounge-team lounge-team_right sys-team-right   lounge-team_RUB "> <div class="lounge-team__info"> <div class="lounge-team__title sys-t2name"> {{match.team2}} </div> <div class="lounge-team__coeff-sum"> <div class="lounge-team__coeff sys-stat-koef-2">x{{match.odd2}}</div> </div> </div> <div class="lounge-team__logo"> <img src="{{match.logo2}}" alt="{{match.team2}}" class="sys-t2logo"> </div> </div> </div> </div> <div class="lounge-match__tournament-img sys-tourney-pic" style="background-image: url('https://csgolounge.com/images/leagues/go/2088_1588030963.png')"></div> </div> </a> </div>

          {% elif match.status == 'Results' %}

                    <div  class="lounge-bets-items__item sys-betting bet_coming 
          {% if match.winner == 'Team 1' %}
         	bet-winner-left 
          {% elif match.winner == 'Team 2' %}
        	bet_winner-right
          {% endif %}"

          data-id="{{match.match_id}}"> 
          <a href="/match/{{match.match_id}}" class="lounge-match"> 
          	<div class="lounge-match__header"> <div class="lounge-match__date ">
          	 <div class="lounge-match-date 
          	 {% if match.status == 'Canceled' %} 
          	 	lounge-match-date_canceled
          	 {% elif match.status == 'Rescheduled' %} 
          	 	lounge-match-date_rescheduled
          	 {% endif %}"> 

          	 <div class="lounge-match-date__date sys-time-fixed"> {{match.date}} </div>
          	 </div> </div> <div class="lounge-match__tournament sys-tourney-name"> Tournoi </div> </div> <div class="lounge-match__body"> <div class="lounge-match__teams-bo"> <div class="lounge-match__team lounge-match__team_left"> 
          	 <div class="lounge-team lounge-team_left sys-team-left 
          	 {% if match.winner == 'Team 1' %}
          	 	lounge-team_win 
          	 {% endif %} 
          	 lounge-team_EUR "> <div class="lounge-team__info"> 
          	 <div class="lounge-team__title sys-t1name"> {{match.team1}} </div> 
          	 <div class="lounge-team__coeff-sum"> <div class="lounge-team__coeff sys-stat-koef-1">x{{match.odd1}}</div>
          	  <div class="lounge-team__sum"> <div ></div> </div> </div> </div> <div class="lounge-team__logo"> 
          	 <img src="{{match.logo1}}" alt="{{match.team1}}" class="sys-t1logo"> </div> </div>
      	 	 </div> <div class="lounge-match__bo sys-bo">  {{match.bo}}  </div> <div class="lounge-match__team lounge-match__team_right"> <div class="lounge-team lounge-team_right
      	 	 {% if match.winner == 'Team 2' %}
      	 	 	lounge-team_win 
      	 	 {% endif %}
      	 	  sys-team-right   lounge-team_EUR "> <div class="lounge-team__info">
      	 	  	<div class="lounge-team__title sys-t2name"> {{match.team2}}</div> <div class="lounge-team__coeff-sum"> <div class="lounge-team__coeff sys-stat-koef-2">x{{match.odd2}}</div> <div class="lounge-team__sum"> <div></div> </div> </div> </div> <div class="lounge-team__logo">
      	 	   <img src="{{match.logo2}}" alt="{{match.team2}}" class="sys-t2logo"> </div> </div> </div> </div> <div class="lounge-match__tournament-img sys-tourney-pic" style="background-image: url('https://csgolounge.com/images/leagues/go/2030_1586056352.png')"></div> </div> </a> </div>



          {% else%}

          <div class="lounge-bets-items__item sys-betting bet-canceled" > <a href="/fr/match/211045/" class="lounge-match"> <div class="lounge-match__header"> <div class="lounge-match__date"> <div class="lounge-match-date  lounge-match-date_canceled  "> <div class="lounge-match-date__date sys-time-fixed"> {{match.date}} </div>   <div class="lounge-match-date__canceled">Match expiré</div>  </div> </div> <div class="lounge-match__tournament sys-tourney-name"> Tournoi </div> </div> <div class="lounge-match__body"> <div class="lounge-match__teams-bo"> <div class="lounge-match__team lounge-match__team_left"> <div class="lounge-team lounge-team_left sys-team-left   lounge-team_RUB "> <div class="lounge-team__info"> <div class="lounge-team__title sys-t1name"> {{match.team1}} </div> <div class="lounge-team__coeff-sum"> <div class="lounge-team__coeff sys-stat-koef-1">x{{match.odd1}}</div> </div> </div> <div class="lounge-team__logo"> <img src="{{match.logo1}}" alt="{{match.team1}}" class="sys-t1logo"> </div> </div> </div> <div class="lounge-match__bo sys-bo">  {{match.bo}}  </div> <div class="lounge-match__team lounge-match__team_right"> <div class="lounge-team lounge-team_right sys-team-right   lounge-team_RUB "> <div class="lounge-team__info"> <div class="lounge-team__title sys-t2name"> {{match.team2}} </div> <div class="lounge-team__coeff-sum"> <div class="lounge-team__coeff sys-stat-koef-2">x{{match.odd2}}</div> </div> </div> <div class="lounge-team__logo"> <img src="{{match.logo2}}" alt="{{match.team2}}" class="sys-t2logo"> </div> </div> </div> </div> <div class="lounge-match__tournament-img sys-tourney-pic" style="background-image: url('https://csgolounge.com/images/leagues/go/2030_1586056352.png')"></div> </div> </a> </div>
          {% endif %}

      	 	   {% endfor %}

{% else %}
    <p>No matches are available.</p>
{% endif %}

paris/templates/paris/index.html
{% extends "paris/base.html" %}



{% block title %}
CSGO auto-bettor
{% endblock %}

{% block matches %}


{% include "paris/upcoming.html" %}

{% endblock %}

{% block predictions %}


<div class="btn-group btn-group-toggle d-flex mb-2" data-toggle="buttons">
  <label class="btn btn-secondary active">
    <input type="radio" name="options" id="evStrat" autocomplete="off" checked> EV strategy
  </label>
  <label class="btn btn-secondary">
    <input type="radio" name="options" id="naiveStrat" autocomplete="off"> Naive Strategy
  </label>
  <label class="btn btn-secondary">
    <input type="radio" name="options" id="kellyStrat" autocomplete="off"> Kelly Strategy
  </label>

</div>

<div class = "bg-success container-fluid rounded" style = "display: none;">
  <form method='post'>
    {% csrf_token %}
<label for="evRange">Expected value threshold</label>
<input type="range" class="custom-range" id="evRange" min= "-0.2" max = "2" step = "0.1" value="0" 
oninput="evOutput.value = evRange.value">

EV ≥ <output id ="evOutput" for ="evRange" >0</output>
</form>
</div>


<br>
<!--
 <div class="btn-group btn-group-toggle d-flex mb-2" data-toggle="buttons">
  <label class="btn btn-secondary active">
    <input type="radio" name="options" id="1DayBet" autocomplete="off" checked> Today
  </label>
  <label class="btn btn-secondary">
    <input type="radio" name="options" id="3DaysBet" autocomplete="off"> Past 3 days
  </label>
  <label class="btn btn-secondary">
    <input type="radio" name="options" id="7DaysBet" autocomplete="off"> Past 7 days
  </label>
</div>

-->
<div id='betlist'>


 </div>


{% endblock %}


{% block script %}


<script>
  
/*var ev= $('#evRange').val();*/
var ev = 0;
var strategy = 'ev';
var date='1';
$('#betlist').load(`bet_history2/${ev}/${strategy}`);

/*
$('#1DayBet').click(function(){
  date = '1';
  console.log(date);
  $('#betlist').load(`bet_history2/${ev}/${date}`);

});


$('#3DaysBet').click(function(){
  date = '3';
  console.log(date);
  $('#betlist').load(`bet_history2/${ev}/${date}`);


});

$('#7DaysBet').click(function(){
  date = '7';
  console.log(date);
  $('#betlist').load(`bet_history2/${ev}/${date}`);
});


*/

$('#evRange').change(function(){

ev = $(this).val();
console.log(date);
$('#betlist').load(`bet_history2/${ev}/${strategy}`);

});

$('#naiveStrat').click(function(){
strategy = 'naive'
$('#betlist').load(`bet_history2/${ev}/${strategy}`)
})

$('#evStrat').click(function(){
strategy = 'ev'
$('#betlist').load(`bet_history2/${ev}/${strategy}`)
})

$('#kellyStrat').click(function(){
strategy = 'kelly'
$('#betlist').load(`bet_history2/${ev}/${strategy}`)
})


</script>

{% endblock %}

paris/templates/paris/pred.html
{% if pred_list %}

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Team 1</th>
      <th scope="col">Odd 1</th>
      <th scope="col">Odd 1 predicted</th>
      <th scope="col">Team 2</th>
      <th scope="col">Odd 2</th>
      <th scope="col">Odd 2 predicted</th>
      <th scope="col">ΔEV1</th>
      <th scope="col">ΔEV2</th>
  </tr>
</thead>
   <tbody>
   	{% for pred in pred_list %}
    <tr>

      <td>{{pred.match.team1}}</td>
      <td>{{pred.match.odd1}}</td>
      <td>{{pred.odd1}}</td>
      <td>{{pred.match.team2}}</td>
      <td>{{pred.match.odd2}}</td>
      <td>{{pred.odd2}}</td>
      <td>{{pred.delta_ev_1}} </td>
      <td>{{pred.delta_ev_2}} </td>
  </tr>

    {% endfor %}
</tbody>
{% else %}
    <p>No predictions are available.</p>
{% endif %}

paris/templates/paris/team_match_list.html
<option value="">---------</option>

<option value="{{ match.team1 }}">{{ match.team1 }}</option>
<option value="{{ match.team2 }}">{{ match.team2}}</option>